### ISSUE TITLE
DiffConflictsShowHistory broke?

### ISSUE THREAD

**Issue by strobelight** [whiteinge/diffconflicts#11]
when I run the DiffConflictsShowHistory, I get errors:

```
Error detected while processing function <SNR>17_checkThenShowHistory:
line    1:
E117: Unknown function: getbufinfo
E116: Invalid arguments for function copy(getbufinfo()), {i, x -> x.name =~# 'BASE' || x.name =~# 'LOCAL' || x.name =~# 'REMOTE'})
E116: Invalid arguments for function filter(copy(getbufinfo()), {i, x -> x.name =~# 'BASE' || x.name =~# 'LOCAL' || x.name =~# 'REMOTE'})
E15: Invalid expression: filter(copy(getbufinfo()), {i, x -> x.name =~# 'BASE' || x.name =~# 'LOCAL' || x.name =~# 'REMOTE'})
line    4:
E121: Undefined variable: l:xs
E116: Invalid arguments for function len(l:xs) < 3)
E15: Invalid expression: (len(l:xs) < 3)
Press ENTER or type command to continue
```

**Comment by whiteinge** [comment]
Thanks for filing the issue. It looks like `getbufinfo ` was added in VIm `7.4.2204` and I'm using lambdas which are a Vim 8 thing. My bad for not adding a version check! That said, I don't need to use either of those for this. What minimum Vim version are you running?

**Comment by whiteinge** [comment]
I think the change in #12 should do the trick. I'd appreciate a confirmation if you have a moment to try it. Then I'll get a new release tagged.

**Comment by whiteinge** [comment]
Merged. Feel free to reopen if the issue persists!
