### ISSUE TITLE
Local and Remote windows swapped??

### ISSUE THREAD

**Issue by jmandawg** [whiteinge/diffconflicts#14]
Sorry don't mean to spam you with multiple issues, but there's no place for general questions.  When i run the example:

```
<<<<<<< HEAD
twas brillig, and the slithy toves
Did gyre and gimble in the wabe:
all mimsy were the borogoves,
And the mome raths outgrabe.
=======
'Twas brillig, and the slithy toves
Did gyre and gimble in the wabe:
All mimsy were the borogroves
And the mome raths outgabe.
>>>>>>> branchA

"Beware the Jabberwock, my son!
The jaws that bite, the claws that catch!
Beware the Jubjub bird, and shun
The frumious Bandersnatch!"

```

I would expect the HEAD section to be the LOCAL (LEFT WINDOW) and branchA (the branch being merged into LOCAL) to be the REMOTE (Right window)  

But for some reason they are swapped.  Is this by design?

I feel it's more natural to be "Left (local) is what i have locally" and "Right (remote) is what I'm merging In"

**Comment by whiteinge** [comment]
Haha, wow. Nope, that's definitely a mistake. After a little Git history sleuthing it looks like this originated as a copy/paste typo during a refactor and has been in place for longer than I'd care to admit.

Thanks a lot for the catch!
