### ISSUE TITLE
vim-diffconflict workflow

### ISSUE THREAD

**Issue by sandangel** [whiteinge/diffconflicts#18]
Hello. Sorry may I ask a stupid question.
When I run `:DiffConflict`, it open a new tab with 2 windows for Left and Right. How could I choose which one to use? I put the cursor at the change I want to pick, ran `:diffget` but vim show an error that modifiable is off.

**Comment by whiteinge** [comment]
Hi. You should see [a message with instructions](https://github.com/whiteinge/diffconflicts/blob/fb2a18230c0e8479a096ad16bd5068e22e6975e0/_utils/vim-diffconflicts.png) that instruct you to move changes to the left like in that screenshot. If that doesn't show up for you I'd be interested to dive into why.

**Comment by sandangel** [comment]
Thank you I saw your instruction video on youtube, I will check it out when I get home.
