### ISSUE TITLE
Help when editing multiple diffs with git mergetool

### ISSUE THREAD

**Issue by tjaartvdwalt** [whiteinge/diffconflicts#24]
Thanks for a great project.

When I have multiple conflicted files, and I run `git mergetool`, diffconflicts successfully edits the first conflicted file, but does not edit any of the subsequent files.
If I try to run `git mergetool` a second time, I get a message that `No files need merging`

After I fixed up the first file I ran `:xa` or `:wqa` (as I see in the Youtube video in the README). Is this the correct command?

The relevant config in my `~/.gitconfig` is

```
[merge]
        tool = diffconflicts
[mergetool "diffconflicts"]
        cmd = vim -c DiffConflicts \"$MERGED\" \"$BASE\" \"$LOCAL\" \"$REMOTE\"
        trustExitCode = true
[mergetool]
        keepBackup = false
```

**Comment by tjaartvdwalt** [comment]
I tested with a different mergetool, and it appears there really only was 1 conflict

I got confused by the message `4 files to edit` apparent in the screenshot below. Now I realize the 4 files, was referring to `"$MERGED\" \"$BASE\" \"$LOCAL\" \"$REMOTE"`, not 4 conflicted files.

![screenshot_2020-06-30_11-58-51_446999250](https://user-images.githubusercontent.com/2066766/86173571-043b0a80-bad5-11ea-9383-a188c03c82e3.png)

**Comment by whiteinge** [comment]
I'm glad you figured it out -- thanks for posting the solution too.

I don't recall noticing that "4 files to edit" bit before but now that you point it out, I agree that's confusing :confused:.
